### PR TITLE
Checkout: Validate and double enter customer email address #450

### PR DESCRIPTION
**Pull request by ankurMalhotra**
Functionality was already implemented. Added unit tests for it. Was
there a reason why ValidateEmailAddress was set to false?

### CODE REVIEW

**Comment by muratcakir** [comment]
It is _false_ on purpose. Anyhow, thanks for contributing.

**Comment by ankurMalhotra** [comment]
Why is it set to false?

**Comment by muratcakir** [comment]
You can turn validation on in **Configuration > Settings > Customer Settings > Address form fields**.

It is set to false because not everyone needs this. If you need it, turn it on... simple.

**Comment by ankurMalhotra** [comment]
Perfect. Can the unit tests be merged?

**Pull request closed without merging**
