### PR TITLE
SMTP without authentication, workaround touch API, use store theme settings for mail styling

### PR DESCRIPTION
**Pull request by rhinterndorfer**

### CODE REVIEW

**Comment by rhinterndorfer** [comment]
What would be a better placement for a Closer?
I will check my e-Mail styling approach.

**Comment by muratcakir** [comment]
> What would be a better placement for a Closer?

It just doesn't look good in the upper tabstrip. Besides, it squashes the tab labels and cuts them in other languages with longer labels. I have no idea where to place it in a hurry.

**Comment by rhinterndorfer** [comment]
The closer now uses times character and is placed outside the nav menu. While my test I have seen that when the screen width is very small the offcanvas-cart menu uses the whole width and therefore the closer is also needed to close the offcanvas-cart without the need of reloading the site. Please check my new suggestion and if you have any ideas to make it looking better please share it with me.

**Comment by rhinterndorfer** [comment]
I have removed the closer and have done a deeper look into the smartstore.offcanvas.js script which is responsible for the menu functionality. I have changed the hiding trigger event from "tap" to "click" and now it works on all device classes (mouse, touch, mixed). I have seen on small devices where the menu uses the whole width that you can close the menu with a swipe gesture. I think this is a good solution for small devices because I think they all have touch screens.

**Comment by rhinterndorfer** [comment]
Should I also revert the mail styling thing for the moment?

**Comment by muratcakir** [comment]
> Should I also revert the mail styling thing for the moment?

Yes, please.

**Comment by rhinterndorfer** [comment]
I have reverted the mail styling thing.

**Pull request merged**
